site_name: Deep Hierarchy
use_directory_urls: false
theme:
  name: material
docs_dir: doc
nav:
  - Home: index.md
  - Examples:
      - Region Adjacency Graph: examples/rag.py
plugins:
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
      no_prompt: true
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
- js/mathjax.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML