[project]
name = "deephierarchy"
version = "0.1.0"
authors = [
    {name = "Baptiste Esteban", email = "baptiste.esteban@epita.fr"}
]
requires-python = ">=3.13"
dependencies = [
    "numba>=0.67.0",
    "numpy>=2.5.3",
]

[project.optional-dependencies]
doc = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "mkdocs>=1.6.1",
    "mkdocs-jupyter>=0.26.3",
    "mkdocs-material>=9.7.7",
    "scikit-image>=0.26.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["I"]
